<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <ApplicationIcon></ApplicationIcon>
    <StartupObject>EnterpriseApp.Program</StartupObject>
    <AssemblyName>EnterpriseApp</AssemblyName>
    <RootNamespace>EnterpriseApp</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SQLite" Version="1.0.118" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\legacy.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Forms\*.cs" />
    <Compile Include="Helpers\*.cs" />
    <Compile Include="Properties\*.cs" />
  </ItemGroup>

</Project>
